In [17]:
import cv2

In [18]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [19]:
img = cv2.imread("kel.jpg")

In [20]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [21]:
faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.05, minNeighbors=5)

In [22]:
print (type(faces))

<class 'numpy.ndarray'>


In [23]:
print (faces)

[[169 100 128 128]
 [458  95 138 138]
 [612 101 142 142]
 [ 25 102 143 143]
 [325 150 118 118]
 [225 269 135 135]
 [500 284 134 134]]


In [24]:
for x,y,w,h in faces :
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (139,139,0),3)

In [25]:
res = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))

In [26]:
cv2.imshow("Gray", res)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>